export const KEY_MAP_IP_API_COM: { [key: string]: string } = {
  continent_name: "continent",
  continent_code: "continentCode",
  country_name: "country",
  country_code: "countryCode",
  region_code: "region",
  region: "regionName",
  city: "city",
  district: "district",
  latitude: "lat",
  longitude: "lon",
  timezone: "timezone",
  offset: "offset",
  currency: "currency",
  isp: "isp",
  org: "org",
  as: "as",
  asname: "asname",
  reverse: "reverse",
  mobile: "mobile",
  hosting: "hosting",
  ip: "query",
  proxy: "proxy",
};
